version: 2

updates:
# Fetch and update latest `npm` packages
- package-ecosystem: npm
  directory: '/packages/swr-global-state'
  target-branch: 'main'
  schedule:
    interval: monthly
    time: '00:00'
  open-pull-requests-limit: 10
  reviewers:
    - gadingnst
  assignees:
    - gadingnst
  commit-message:
    prefix: fix
    prefix-development: chore
    include: scope
