name: Continuous Integration
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  install:
    name: Install Dependency
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.event.pull_request.head.sha }}
      - name: Use Node.js 18.x
        uses: actions/setup-node@v1
        with:
          node-version: 18.x
      - name: Cache node modules
        uses: actions/cache@v1
        with:
          path: node_modules
          key: node_modules-${{ github.event.pull_request.head.sha }}
          restore-keys: |
            node_modules-
      - name: Install Dependency Package
        run: |
          npm install

  test:
    name: Unit Test
    if: github.event_name == 'pull_request'
    needs: install
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.event.pull_request.head.sha }}
      - name: Load node_modules
        uses: actions/cache@v1
        with:
          path: node_modules
          key: node_modules-${{ github.event.pull_request.head.sha }}
      - name: Start Unit Testing
        run: |
          npm run test:coverage
      - name: Generate Coverage Report
        uses: davelosert/vitest-coverage-report-action@v2
        if: always()
        with:
          json-summary-path: './packages/swr-global-state/coverage/coverage-summary.json'
          json-final-path: './packages/swr-global-state/coverage/coverage-final.json'
          vite-config-path: './packages/swr-global-state/vitest.config.ts'
          working-directory: './packages/swr-global-state'

  build:
    name: Build
    if: github.event_name == 'push'
    needs: install
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.event.pull_request.head.sha }}
      - name: Load node_modules
        uses: actions/cache@v1
        with:
          path: node_modules
          key: node_modules-${{ github.event.pull_request.head.sha }}
      - name: Start Building
        run: |
          npm run build

  size:
    name: Build & Generate Size report
    if: github.event_name == 'pull_request'
    needs: install
    runs-on: ubuntu-latest
    env:
      CI_JOB_NUMBER: 1
    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.event.pull_request.head.sha }}
      - name: Load node_modules
        uses: actions/cache@v1
        with:
          path: node_modules
          key: node_modules-${{ github.event.pull_request.head.sha }}
      - uses: andresz1/size-limit-action@v1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          skip_step: install
          directory: packages/swr-global-state
